#!/bin/bash

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -e /var/run/my_process.pid ]; then
            PID=$(cat /var/run/my_process.pid)
            kill $PID
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

